name: Build, Test, and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Run security tests
      run: npm run security-test

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: FelipeHldr/teste:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull Docker image from Docker Hub
      run: docker pull FelipeHldr/teste:latest

    - name: Run Docker container
      run: docker run -d -p 8080:8080 FelipeHldr/teste:latest

    - name: Expose container with ngrok
      uses: w9jds/ngrok-action@v1
      with:
        authtoken: ${{ secrets.NGROK_AUTH_TOKEN }}
        region: us
        addr: http://localhost:8080

